on:
  issue_comment:
    types: [created]

name: doc-preview.yaml

permissions: read-all

jobs:
  preview:
    if: ${{ github.event.issue.pull_request && (github.event.comment.author_association == 'COLLABORATOR' || github.event.comment.author_association == 'CONTRIBUTOR' || github.event.comment.author_association == 'MEMBER' || github.event.comment.author_association == 'OWNER') && startsWith(github.event.comment.body, '/preview-docs') }}

    runs-on: ubuntu-latest
    permissions:
      # Needed to write a comment on the PR
      pull-requests: write
      # Needed to read the PR branch
      contents: read
    steps:
      - uses: actions/checkout@v4
        with:
          # Checkout the PR branch
          ref: refs/pull/${{ github.event.issue.number }}/head

      - uses: r-lib/actions/setup-pandoc@v2

      - uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true

      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: any::pkgdown, local::.
          needs: website

      - name: Build site
        run: pkgdown::build_site_github_pages(new_process = FALSE, install = FALSE)
        shell: Rscript {0}

      - name: Deploy to Netlify
        uses: nwtgck/actions-netlify@v3.0
        with:
          # Standard config
          github-token: ${{ secrets.GITHUB_TOKEN }}
          deploy-message: "Deploy from GitHub Actions"
          # 'docs/' is the default directory for pkgdown::build_site()
          # we add 'dev' because _pkgdown.yml has 'development: mode: devel'
          publish-dir: './docs/dev'
          # Development deploys only
          production-deploy: false
          # Enable pull request comment (default)
          enable-pull-request-comment: true
          # Overwrite the pull request comment with updated link (default)
          overwrites-pull-request-comment: true
          # Don't deploy to GitHub
          enable-github-deployment: false
          # Don't update the status of the commit
          enable-commit-status: false
          # Don't comment on the commit
          enable-commit-comment: false
        env:
          # Netlify credentials (currently from Dmitry's account)
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
        timeout-minutes: 1
